### ISSUE TITLE
Produce consistent code generation in Java 8 and Java 7

### ISSUE THREAD

**Issue by azzoti** [uglycustard/buildergenerator#42]
The order in which methods are generated changes between Java 7 and Java 8. If Java 8 is used, several unit tests in BuilderGeneratorIT fail because of the ordering of generated methods. For example with Java 8 BuilderGeneratorIT#beanWithNonGenericCollectionsProperty fails.

Its because of WithMethodList's use of org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptors(targetClass). The order of fields returned changes between Java 7 and Java 8.

Under Java 7, the order of the fields returned by org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptors( BeanWithNonGenericCollections.class) is
- beans
- things
- class
- stuff

But under Java 8 it is:
- stuff
- beans
- class
- things

I suggest that the fields should be ordered in some consistent way so that methods are generated in a consistent order.

```java
package uk.co.buildergenerator.integrationtest;

import java.beans.PropertyDescriptor;

import org.apache.commons.beanutils.PropertyUtils;

import uk.co.buildergenerator.testmodel.BeanWithNonGenericCollections;

public class Main {

	public static void main(String[] args) {
		for (PropertyDescriptor propertyDescriptor : PropertyUtils
				.getPropertyDescriptors(BeanWithNonGenericCollections.class)) {

			System.out.println(propertyDescriptor.getDisplayName());
		}
	}
}
```

Extra problem with Java 8. The maven javadoc plugin is more strict under java 8. The use of `<br/>` and `<p/>` is not allowed as it is not valid HTML5.

**Comment by uglycustard** [comment]
Hi Tim,
Fork it (which you already have!), fix it, then send me a pull request.
If we can make it order agnostic that would be even better I think?

Cheers,Matt
 

    On Thursday, 2 June 2016, 8:37, Tim Azzopardi <notifications@github.com> wrote:
 

 The order in which methods are generated changes between Java 7 and Java 8. If Java 8 is used, several unit tests in BuilderGeneratorIT fail because of the ordering of generated methods. For example with Java 8 BuilderGeneratorIT#beanWithNonGenericCollectionsProperty fails.Its because of WithMethodList's use of org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptors(targetClass). The order of fields returned changes between Java 7 and Java 8.Under Java 7, the order of the fields returned by org.apache.commons.beanutils.PropertyUtils.getPropertyDescriptors( BeanWithNonGenericCollections.class) is   
   - beans
   - things
   - class
   - stuff
But under Java 8 it is:   
   - stuff
   - beans
   - class
   - things
I suggest that the fields should be ordered in some consistent way so that methods are generated in a consistent order.package uk.co.buildergenerator.integrationtest;

import java.beans.PropertyDescriptor;

import org.apache.commons.beanutils.PropertyUtils;

import uk.co.buildergenerator.testmodel.BeanWithNonGenericCollections;

public class Main {

    public static void main(String[] args) {
        for (PropertyDescriptor propertyDescriptor : PropertyUtils
                .getPropertyDescriptors(BeanWithNonGenericCollections.class)) {

            System.out.println(propertyDescriptor.getDisplayName());
        }
    }
}—

**Comment by azzoti** [comment]
Re: "If we can make it order agnostic that would be even better I think?"

s/agnostic/independent/?

But even then...

- If you mean make the integration tests pass in a way that is *independent*
of the order of the methods in the generated code, then that would be hard.
The integration tests are currently written to use a simple file compare,
so at least the failing (and to be safe all the) IT tests would need to
change substantially.

- If you mean make BG generate the methods in a predictable order that
is *independent
*of the order of the return PropertyUtils#getPropertyDescriptors then that
would be easy: the properties could be ordered alphabetically by name.

IMO a predictable order of generated methods would be best. IMO It should
NOT be OK for BG generated methods to jump around in the source file if the
version of the JRE or Apache beanutils changes.

**Comment by uglycustard** [comment]
Yeah, good point. Want to give it a go?

**Comment by azzoti** [comment]
Sure!

**Comment by uglycustard** [comment]
Release 1.0.1
